version: "3"
services:
  filter_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: filter_app_image
    container_name: filter_app_container
    restart: unless-stopped
    env_file: docker.env
    ports:
      - "3080:3080"
    volumes:
      - ./src:/usr/src/app/src
      - productImages:/root/src/public/images
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: project_db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  pgdata:
  productImages:

